POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2NTZlMThjNDJmNjI0NjE5YjkwNTgwZDAiLCJpYXQiOjE3MDE3NzgzNDl9.vKcLS3ZXhFrGfaDKWvZ71xsJLFM3aw7Dtbi8SOGRunQ

{
"title": "asdas John",
"author": "asdas Kowalski",
"url": "asdaas",
"likes": 20
}
###
